# Generated by Django 6.0.7 on 2026-07-18 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField()),
                ('file_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('candidate_name', models.CharField(blank=True, max_length=200)),
                ('candidate_email', models.EmailField(max_length=254)),
                ('processed', models.BooleanField(default=False)),
            ],
        ),
    ]
